package io.legado.app.data.repository

import androidx.test.platform.app.InstrumentationRegistry
import io.legado.app.data.appDb
import io.legado.app.data.entities.ReplaceRule
import io.legado.app.help.config.ReplacePreviewConfig
import io.legado.app.model.RuleUpdate
import io.legado.app.utils.GSON
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import org.junit.Assert.*
import org.junit.Test
import java.io.File
import java.util.UUID

class ReplaceRuleImportRepositoryTest {
    private val context = InstrumentationRegistry.getInstrumentation().targetContext
    @Test fun cachedUrlIsConsumedAndMoreThan900IdsCompareWithoutSelectingUpdatesOrMutatingCacheEntities() = runBlocking {
        val base = System.nanoTime(); val session = UUID.randomUUID().toString()
        val url = "https://replace-import-${UUID.randomUUID()}.invalid/rules"
        val existing = List(901) { ReplaceRule(id = base + it, name = "Stored $it", pattern = "old", replacement = "old", isRegex = false) }
        val fresh = ReplaceRule(id = base + 902, name = "Fresh", pattern = "new", replacement = "new", isRegex = false)
        fresh.previewText = "preview before replacement"
        val incoming = existing.map { it.copy(pattern = "different") } + fresh
        val repo = AppReplaceRuleImportRepository(context)
        try {
            withContext(Dispatchers.IO) { appDb.replaceRuleDao.insert(*existing.toTypedArray()) }
            RuleUpdate.cacheReplaceRuleMap[url] = incoming
            val items = repo.read(url)
            assertFalse(RuleUpdate.cacheReplaceRuleMap.containsKey(url)); assertEquals(902, items.size)
            assertTrue(items.take(901).all { it.status == ReplaceRuleImportStatus.Update && !it.selectedByDefault })
            assertTrue(items.last().selectedByDefault)
            repo.stage(session, items); assertEquals(ReplaceRuleImportSession(items), repo.restore(session))
            repo.insert(session, items, setOf(items.last().key), "imported", false)
            withContext(Dispatchers.IO) {
                assertEquals("old", appDb.replaceRuleDao.findById(base)!!.pattern)
                assertEquals("imported", appDb.replaceRuleDao.findById(fresh.id)!!.group)
                assertEquals("preview before replacement", ReplacePreviewConfig.sample(fresh.id))
            }
            assertNull(fresh.group); assertTrue(repo.restore(session)!!.committed)
        } finally {
            RuleUpdate.cacheReplaceRuleMap.remove(url)
            withContext(Dispatchers.IO) { appDb.replaceRuleDao.delete(*(existing + fresh).toTypedArray()); ReplacePreviewConfig.removeSample(fresh.id) }
            File(context.cacheDir, "replace-rule-import/$session.json").delete()
        }
    }
    @Test fun groupAppendDeduplicatesAndAutoGeneratedRoomIdReceivesTheSampleWithoutChangingStagedPayload() = runBlocking {
        val session = UUID.randomUUID().toString(); val name = "Generated-${UUID.randomUUID()}"
        val rule = ReplaceRule(id = 0, name = name, group = " A;B，A； ", pattern = "target", replacement = "changed", isRegex = false)
        rule.previewText = "target sample"
        val repo = AppReplaceRuleImportRepository(context)
        try {
            val items = repo.read(GSON.toJson(rule)); repo.stage(session, items)
            repo.insert(session, items, setOf(items.single().key), " B ", true)
            withContext(Dispatchers.IO) {
                val saved = appDb.replaceRuleDao.all.single { it.name == name }
                assertTrue(saved.id > 0); assertEquals("A,B", saved.group)
                assertEquals("target sample", ReplacePreviewConfig.sample(saved.id))
            }
            assertEquals(GSON.toJson(rule), repo.restore(session)!!.items.single().json)
        } finally {
            withContext(Dispatchers.IO) {
                appDb.replaceRuleDao.all.filter { it.name == name }.forEach {
                    appDb.replaceRuleDao.delete(it); ReplacePreviewConfig.removeSample(it.id)
                }
            }
            File(context.cacheDir, "replace-rule-import/$session.json").delete()
        }
    }
    @Test fun legacyJsonUriAndCodeEditRetainCompatibilityAndDoNotWriteUntilConfirm() = runBlocking {
        val id = System.nanoTime(); val source = File(context.cacheDir, "replace-source-${UUID.randomUUID()}.json")
        val legacy = """{"id":$id,"regex":"target","replaceSummary":"Legacy","replacement":"changed","isRegex":false,"useTo":"scope","enable":true,"serialNumber":23}"""
        val repo = AppReplaceRuleImportRepository(context)
        try {
            withContext(Dispatchers.IO) { source.writeText(legacy) }
            val items = repo.read(android.net.Uri.fromFile(source).toString())
            val item = items.single(); assertEquals("Legacy", item.name)
            val parsed = GSON.fromJson(item.json, ReplaceRule::class.java)
            assertEquals("target", parsed.pattern); assertEquals("scope", parsed.scope); assertEquals(23, parsed.order)
            assertEquals(item, repo.edit(item.key, item.json))
            assertTrue(runCatching { repo.edit(item.key, "invalid") }.isFailure)
            withContext(Dispatchers.IO) { assertNull(appDb.replaceRuleDao.findById(id)) }
        } finally { source.delete() }
    }
}
