package io.legado.app.ui.book.search

internal data class BookSearchActions(
    val close: () -> Unit = {},
    val query: (String, Int, Int) -> Unit = { _, _, _ -> },
    val focus: (Boolean) -> Unit = {},
    val submit: () -> Unit = {},
    val stop: () -> Unit = {},
    val continueSearch: (Boolean) -> Unit = {},
    val history: (String) -> Unit = {},
    val deleteHistory: (String) -> Unit = {},
    val clearHistoryPrompt: (Boolean) -> Unit = {},
    val clearHistory: () -> Unit = {},
    val result: (String) -> Unit = {},
    val suggestion: (String) -> Unit = {},
    val precision: () -> Unit = {},
    val readRecords: () -> Unit = {},
    val openFilter: () -> Unit = {},
    val filter: (String, Int) -> Unit = { _, _ -> },
    val dismissFilter: () -> Unit = {},
    val confirmFilter: () -> Unit = {},
    val sources: () -> Unit = {},
    val scope: () -> Unit = {},
    val group: (String) -> Unit = {},
    val allSources: () -> Unit = {},
    val openedMenu: () -> Unit = {},
    val log: () -> Unit = {},
    val retry: () -> Unit = {},
    val dismissEmpty: () -> Unit = {},
    val confirmEmpty: () -> Unit = {},
)
